version: '3.8'

services:
    db:
        image: mysql
        container_name: db_docker_symfony
        restart: always
        volumes:
          - db-data:/var/lib/mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - db
        ports:
          - 8000:80
        environment:
            PMA_HOST: db
        networks:
          - dev
    php:
      container_name: php_82
      build:
        context: ./php
      ports:
        - '9000:9000'
      volumes:
        - ./project:/var/www/symfony_docker
      networks:
        - dev

    nginx:
      container_name: nginx
      image: nginx:stable-alpine
      ports:
        - '8080:80'
      volumes:
        - ./project:/var/www/symfony_docker
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
      networks:
        - dev
    maildev:
      image: maildev/maildev
      container_name: maildev_docker_symfony
      command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
      ports:
        - 8001:80
      restart: always
      networks:
          - dev

networks:
    dev:

volumes:
  db-data: