when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'

sentry:
  dsn: "%env(SENTRY_DSN)%"
  register_error_listener: false
  options:
    traces_sample_rate: 0.1

monolog:
  handlers:
    sentry:
      type: sentry
      hub_id: Sentry\State\HubInterface

#        If you are using Monolog, you also need this additional configuration to log the errors correctly:
#        https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
#        register_error_listener: false
#        register_error_handler: false

#    monolog:
#        handlers:
#            sentry:
#                type: sentry
#                level: !php/const Monolog\Logger::ERROR
#                hub_id: Sentry\State\HubInterface
